K-Means x Hierárquico x DBSCAN

In [42]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import DBSCAN
from sklearn.cluster import KMeans

In [43]:
from sklearn import datasets

In [44]:
x_random, y_random = datasets.make_moons(n_samples=1500, noise= 0.09)

In [45]:
x_random

array([[ 1.85607332,  0.27912999],
       [ 0.59146079, -0.20798137],
       [-1.09999708,  0.19193977],
       ...,
       [ 1.48420874, -0.35018279],
       [ 1.95160145,  0.34209934],
       [-0.27909961,  0.8984523 ]])

In [46]:
y_random

array([1, 1, 0, ..., 1, 1, 0])

In [47]:
np.unique(y_random)

array([0, 1])

In [48]:
grafico = px.scatter(x = x_random[:,0], y = x_random[:,1])
grafico.show()

In [51]:
kmeans = KMeans(n_clusters=2)
rotulos = kmeans.fit_predict(x_random)
grafico = px.scatter(x = x_random[:,0], y = x_random[:,1], color = rotulos)
grafico.show()

In [53]:
hc = AgglomerativeClustering(n_clusters= 2, affinity= 'euclidean', linkage= 'ward')
rotulos = hc.fit_predict(x_random)
grafico = px.scatter(x = x_random[:,0], y = x_random[:,1], color = rotulos)
grafico.show()

In [54]:
dbscan = DBSCAN(eps=0.1)
rotulos = dbscan.fit_predict(x_random)
grafico = px.scatter(x= x_random[:,0], y= x_random[:,1], color = rotulos)
grafico.show()