Salvar um Classificador já treinado

In [46]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
import numpy as np
import pandas as pd
import pickle

In [47]:
with open('../credit.pkl', 'rb') as f:
    x_credit_treinamento, y_credit_treinamento, x_credit_teste, y_credit_teste = pickle.load(f)

In [48]:
x_credit_treinamento.shape, y_credit_treinamento.shape

((1500, 3), (1500,))

In [49]:
x_credit_teste.shape, y_credit_teste.shape

((500, 3), (500,))

In [50]:
x_credit = np.concatenate((x_credit_treinamento, x_credit_teste), axis = 0)
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste), axis = 0)

In [51]:
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [52]:
classificador_rede_neural = MLPClassifier(activation='relu', batch_size=56, solver='adam')
classificador_rede_neural.fit(x_credit, y_credit)

/home/breno/Projetos/CursoMachineLearning/machine/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(batch_size=56)

In [53]:
classificador_arvore = DecisionTreeClassifier(criterion='entropy', min_samples_leaf=1, min_samples_split=5, splitter='best')
classificador_arvore.fit(x_credit, y_credit)

DecisionTreeClassifier(criterion='entropy', min_samples_split=5)

In [54]:
classificador_svm = SVC(C=2, kernel='rbf', probability=True)
classificador_svm.fit(x_credit, y_credit)

SVC(C=2, probability=True)

In [55]:
import pickle
pickle.dump(classificador_rede_neural, open('rede_neural_finalizado.sav', 'wb'))
pickle.dump(classificador_arvore, open('arvore_finalizado.sav', 'wb'))
pickle.dump(classificador_svm, open('svm_finalizado.sav', 'wb'))

Carregar um classificador já treinado

In [56]:
rede_neural = pickle.load(open('rede_neural_finalizado.sav', 'rb'))
arvore = pickle.load(open('arvore_finalizado.sav', 'rb'))
svm = pickle.load(open('svm_finalizado.sav', 'rb'))

In [57]:
novo_registro = x_credit[0]
novo_registro

array([-1.3754462 ,  0.50631087,  0.10980934])

In [58]:
novo_registro.shape

(3,)

In [59]:
novo_registro = novo_registro.reshape(1, -1)
novo_registro.shape

(1, 3)

In [60]:
resposta_rede_neural = rede_neural.predict(novo_registro)

In [61]:
resposta_arvore = arvore.predict(novo_registro)

In [62]:
resposta_svm = svm.predict(novo_registro)

In [63]:
paga = 0
nao_paga = 0

if resposta_rede_neural[0] == 1:
    nao_paga += 1
else:
    paga += 1

if resposta_arvore[0] == 1:
    nao_paga += 1
else:
    paga += 1

if resposta_svm[0] ==1:
    nao_paga += 1
else:
    paga += 1


if paga > nao_paga:
    print('Cliente pagará o emprestimo')
elif paga == nao_paga:
    print('Empate')
else:
    print('Cliente não paragá o emprestimo')


Cliente pagará o emprestimo


Rejeição de classificadores

In [64]:
novo_registro = x_credit[0]
novo_registro = novo_registro.reshape(1, -1)
novo_registro, novo_registro.shape

(array([[-1.3754462 ,  0.50631087,  0.10980934]]), (1, 3))

In [65]:
resposta_rede_neural = rede_neural.predict(novo_registro)
resposta_arvore = arvore.predict(novo_registro)
resposta_svm = svm.predict(novo_registro)

In [66]:
resposta_rede_neural[0], resposta_arvore[0], resposta_svm[0]

(0, 0, 0)

In [67]:
probabilidade_rede_neural = rede_neural.predict_proba(novo_registro)
probabilidade_rede_neural

array([[1.00000000e+00, 4.00586179e-16]])

In [68]:
confianca_rede_neural = probabilidade_rede_neural.max()
confianca_rede_neural

0.9999999999999996

In [69]:
probabilidade_arvore = arvore.predict_proba(novo_registro)
confianca_arvore = probabilidade_arvore.max()
confianca_arvore

1.0

In [70]:
probabilidade_svm = svm.predict_proba(novo_registro)
confianca_svm = probabilidade_svm.max()
confianca_svm

0.9999974862820838

In [73]:
paga = 0
nao_paga = 0
confianca_minima = 0.999999
algoritmos = 0

if confianca_rede_neural >= confianca_minima:
    algoritmos += 1
    if resposta_rede_neural[0] == 1:
        nao_paga += 1
    else:
        paga += 1

if confianca_arvore >= confianca_minima:
    algoritmos += 1
    if resposta_arvore[0] == 1:
        nao_paga += 1
    else:
        paga += 1

if confianca_svm >= confianca_minima:
    algoritmos += 1
    if resposta_svm[0] ==1:
        nao_paga += 1
    else:
        paga += 1


if paga > nao_paga:
    print('Cliente pagará o emprestimo, baseado em {}'.format(algoritmos))
elif paga == nao_paga:
    print('Empate, baseado em {}'.format(algoritmos))
else:
    print('Cliente não paragá o emprestimo, baseado em {}'.format(algoritmos))


Cliente pagará o emprestimo, baseado em 2
