Redes Neurais Artificiais

In [2]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

Base Plano de Saúde

In [3]:
base_plano_saude2 = pd.read_csv('../plano_saude2.csv')
x_plano_saude2 = base_plano_saude2.iloc[:, 0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:, 1].values

In [4]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x_plano_saude2_scaled = scaler_x.fit_transform(x_plano_saude2)
scaler_y = StandardScaler()
y_plano_saude2_scaled = scaler_y.fit_transform(y_plano_saude2.reshape(-1, 1))

In [7]:
x_plano_saude2_scaled

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [8]:
y_plano_saude2_scaled

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [13]:
from sklearn.neural_network import MLPRegressor
regressor_rna_saude = MLPRegressor(max_iter=1000)
regressor_rna_saude.fit(x_plano_saude2_scaled, y_plano_saude2_scaled.ravel())

MLPRegressor(max_iter=1000)

In [14]:
regressor_rna_saude.score(x_plano_saude2_scaled, y_plano_saude2_scaled)

0.9620481426534861

In [15]:
grafico = px.scatter(x = x_plano_saude2_scaled.ravel(), y = y_plano_saude2_scaled.ravel())
grafico.add_scatter(x = x_plano_saude2_scaled.ravel(), y = regressor_rna_saude.predict(x_plano_saude2_scaled), name = 'Redes Neurais Artificiais')
grafico.show()

In [16]:
novo = [[40]]
novo = scaler_x.transform(novo)
novo

array([[-0.03481553]])

In [19]:
scaler_y.inverse_transform(regressor_rna_saude.predict(novo).reshape(-1, 1))

array([[1180.6804205]])

Base Preço das Casas - 76064.2218 - 87,67

In [5]:
base_casas = pd.read_csv('../house_prices.csv')
x_casas = base_casas.iloc[:, 3:19].values
y_casas = base_casas.iloc[: ,2].values
x_casas_treinamento, x_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(x_casas, y_casas, test_size = 0.3, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
scaler_x_casas = StandardScaler()
x_casas_treinamento_scaler = scaler_x_casas.fit_transform(x_casas_treinamento)
scaler_y_casas = StandardScaler()
y_casas_treinamento_scaler = scaler_y_casas.fit_transform(y_casas_treinamento.reshape(-1,1))

In [25]:
x_casas_teste_scaler = scaler_x_casas.fit_transform(x_casas_teste)
y_casas_teste_scaler = scaler_y_casas.fit_transform(y_casas_teste.reshape(-1,1))

In [20]:
x_casas_treinamento_scaler.shape

(15129, 16)

In [21]:
x_casas_treinamento_scaler

array([[ 0.67170039, -0.79711466, -0.74522967, ...,  1.03727271,
         1.17348387, -0.83797629],
       [-0.38696772, -0.79711466, -0.68028398, ...,  1.03727271,
         1.53476983, -0.95879989],
       [ 1.7303685 ,  0.82292131,  0.84593978, ..., -0.48008241,
         1.07108346,  0.78248142],
       ...,
       [-0.38696772,  0.17490692,  0.30472568, ..., -0.66741021,
        -1.25528083,  0.3986888 ],
       [ 0.67170039, -0.14910028,  0.31554996, ..., -1.43545415,
        -1.99443873, -0.46129094],
       [ 0.67170039,  0.17490692,  0.32637425, ..., -1.3043247 ,
         0.38168351,  0.66876509]])

In [22]:
y_casas_treinamento_scaler

array([[-0.38454326],
       [-0.3024967 ],
       [ 0.49062008],
       ...,
       [-0.29976181],
       [-0.35445952],
       [ 0.43564888]])

In [27]:
x_casas_teste_scaler.shape

(6484, 16)

In [29]:
regressor_rna_saude = MLPRegressor(max_iter=1000, hidden_layer_sizes=(9,9))
regressor_rna_saude.fit(x_casas_treinamento_scaler, y_casas_treinamento_scaler.ravel())

MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=1000)

In [30]:
regressor_rna_saude.score(x_casas_treinamento_scaler, y_casas_treinamento_scaler)

0.89273788467919

In [31]:
regressor_rna_saude.score(x_casas_teste_scaler, y_casas_teste_scaler)

0.8767797249534037

In [32]:
previsoes = regressor_rna_saude.predict(x_casas_teste_scaler)
previsoes

array([-0.67795058,  3.80812927,  0.08493077, ..., -0.60804879,
       -0.89669165, -0.88582254])

In [33]:
y_casas_teste_scaler

array([[-0.65279094],
       [ 2.80442566],
       [ 0.06267207],
       ...,
       [-0.42878706],
       [-0.73105736],
       [-0.89838556]])

In [36]:
y_casas_teste_inverse = scaler_y_casas.inverse_transform(y_casas_teste_scaler)
previsoes_inverse = scaler_y_casas.inverse_transform(previsoes.reshape(-1, 1))

In [37]:
y_casas_teste_inverse

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [38]:
previsoes_inverse

array([[ 287677.61656422],
       [1949901.58113397],
       [ 570347.49899962],
       ...,
       [ 313578.27651204],
       [ 206627.6433286 ],
       [ 210654.97038188]])

In [39]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_casas_teste_inverse, previsoes_inverse)

76064.22180328515