SVM

In [195]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

Base Plano de Saúde

In [196]:
base_plano_saude2 = pd.read_csv('../plano_saude2.csv')
x_plano_saude2 = base_plano_saude2.iloc[:, 0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:, 1].values
x_teste_arvore = np.arange(min(x_plano_saude2), max(x_plano_saude2), 0.1)
x_teste_arvore = x_teste_arvore.reshape(-1, 1)

In [197]:
x_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [198]:
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [199]:
# Kernel Linear
from sklearn.svm import SVR
regressor_svr_saude_linear = SVR(kernel = 'linear')
regressor_svr_saude_linear.fit(x_plano_saude2, y_plano_saude2)

SVR(kernel='linear')

In [200]:
grafico = px.scatter(x= x_plano_saude2.ravel(), y= y_plano_saude2)
grafico.add_scatter(x= x_teste_arvore.ravel(), y= regressor_svr_saude_linear.predict(x_teste_arvore), name= 'Regressão')
grafico.show()

In [201]:
# Kernel Polinomial
regressor_svr_saude_poly = SVR(kernel='poly', degree=4)
regressor_svr_saude_poly.fit(x_plano_saude2, y_plano_saude2)

SVR(degree=4, kernel='poly')

In [202]:
grafico = px.scatter(x= x_plano_saude2.ravel(), y= y_plano_saude2)
grafico.add_scatter(x= x_teste_arvore.ravel(), y= regressor_svr_saude_poly.predict(x_teste_arvore), name= 'Regressão')
grafico.show()

In [203]:
# Kernel rbf
regressor_svr_saude_rbf = SVR(kernel='rbf')
regressor_svr_saude_rbf.fit(x_plano_saude2, y_plano_saude2)

SVR()

In [204]:
grafico = px.scatter(x= x_plano_saude2.ravel(), y= y_plano_saude2.ravel())
grafico.add_scatter(x= x_plano_saude2.ravel(), y= regressor_svr_saude_rbf.predict(x_plano_saude2), name= 'Regressão')
grafico.show()

In [205]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x_plano_saude2_scaled = scaler_x.fit_transform(x_plano_saude2)
scaler_y = StandardScaler()
y_plano_saude2_scaled = scaler_y.fit_transform(y_plano_saude2.reshape(-1, 1))

In [206]:
x_plano_saude2_scaled

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [207]:
y_plano_saude2_scaled

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [208]:
# Kernel rbf com escala
regressor_svr_saude_rbf_scaled = SVR(kernel='rbf')
regressor_svr_saude_rbf_scaled.fit(x_plano_saude2_scaled, y_plano_saude2_scaled.ravel())

SVR()

In [209]:
grafico = px.scatter(x= x_plano_saude2_scaled.ravel(), y= y_plano_saude2_scaled.ravel())
grafico.add_scatter(x= x_plano_saude2_scaled.ravel(), y= regressor_svr_saude_rbf_scaled.predict(x_plano_saude2_scaled), name= 'Regressão')
grafico.show()

In [210]:
novo = [[40]]

In [211]:
novo = scaler_x.transform(novo)
novo

array([[-0.03481553]])

In [212]:
regressor_svr_saude_rbf_scaled.predict(novo)

array([-0.42259356])

In [213]:
regressor_svr_saude_rbf_scaled.predict(novo).reshape(-1,1)

array([[-0.42259356]])

In [214]:
scaler_y.inverse_transform(regressor_svr_saude_rbf_scaled.predict(novo).reshape(-1,1))

array([[1333.85650748]])

Base Preço das Casas - 83085.3090 - 73,39

In [215]:
base_casas = pd.read_csv('../house_prices.csv')
x_casas = base_casas.iloc[:, 3:19].values
y_casas = base_casas.iloc[: ,2].values
x_casas_treinamento, x_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(x_casas, y_casas, test_size = 0.3, random_state = 0)

In [216]:
x_casas_treinamento.shape

(15129, 16)

In [217]:
x_casas_treinamento

array([[ 4.00000e+00,  1.50000e+00,  1.39000e+03, ...,  9.81330e+04,
         4.77224e+01, -1.22332e+02],
       [ 3.00000e+00,  1.50000e+00,  1.45000e+03, ...,  9.81330e+04,
         4.77725e+01, -1.22349e+02],
       [ 5.00000e+00,  2.75000e+00,  2.86000e+03, ...,  9.80520e+04,
         4.77082e+01, -1.22104e+02],
       ...,
       [ 3.00000e+00,  2.25000e+00,  2.36000e+03, ...,  9.80420e+04,
         4.73856e+01, -1.22158e+02],
       [ 4.00000e+00,  2.00000e+00,  2.37000e+03, ...,  9.80010e+04,
         4.72831e+01, -1.22279e+02],
       [ 4.00000e+00,  2.25000e+00,  2.38000e+03, ...,  9.80080e+04,
         4.76126e+01, -1.22120e+02]])

In [218]:
y_casas_treinamento

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

In [219]:
x_casas_teste.shape

(6484, 16)

In [220]:
from sklearn.preprocessing import StandardScaler
scaler_x_casas = StandardScaler()
x_casas_treinamento_scaler = scaler_x_casas.fit_transform(x_casas_treinamento)
scaler_y_casas = StandardScaler()
y_casas_treinamento_scaler = scaler_y_casas.fit_transform(y_casas_treinamento.reshape(-1,1))

In [221]:
x_casas_treinamento_scaler

array([[ 0.67170039, -0.79711466, -0.74522967, ...,  1.03727271,
         1.17348387, -0.83797629],
       [-0.38696772, -0.79711466, -0.68028398, ...,  1.03727271,
         1.53476983, -0.95879989],
       [ 1.7303685 ,  0.82292131,  0.84593978, ..., -0.48008241,
         1.07108346,  0.78248142],
       ...,
       [-0.38696772,  0.17490692,  0.30472568, ..., -0.66741021,
        -1.25528083,  0.3986888 ],
       [ 0.67170039, -0.14910028,  0.31554996, ..., -1.43545415,
        -1.99443873, -0.46129094],
       [ 0.67170039,  0.17490692,  0.32637425, ..., -1.3043247 ,
         0.38168351,  0.66876509]])

In [222]:
y_casas_treinamento_scaler

array([[-0.38454326],
       [-0.3024967 ],
       [ 0.49062008],
       ...,
       [-0.29976181],
       [-0.35445952],
       [ 0.43564888]])

In [223]:
x_casas_teste_scaler = scaler_x_casas.fit_transform(x_casas_teste)
y_casas_teste_scaler = scaler_y_casas.fit_transform(y_casas_teste.reshape(-1,1))

In [224]:
x_casas_teste_scaler

array([[-1.54541664, -0.80087846, -0.72129133, ...,  0.86153518,
         1.16602473, -0.54260791],
       [ 0.68905353,  1.48142652,  2.85638133, ..., -1.36981856,
         0.53550005,  0.35029279],
       [-1.54541664, -1.77900916, -0.71024913, ...,  0.52683212,
         0.79363917, -1.06700991],
       ...,
       [-0.42818155,  0.50329582,  0.07374704, ..., -0.38430399,
        -0.79207257,  0.8817813 ],
       [-0.42818155, -0.47483489, -0.66608033, ..., -0.86776397,
        -1.41175108, -0.47174278],
       [-0.42818155, -1.45296559, -0.84275552, ...,  0.2479129 ,
        -1.80004438,  0.21564903]])

In [225]:
y_casas_teste_scaler

array([[-0.65279094],
       [ 2.80442566],
       [ 0.06267207],
       ...,
       [-0.42878706],
       [-0.73105736],
       [-0.89838556]])

In [227]:
x_casas_treinamento_scaler.shape, y_casas_treinamento_scaler.shape

((15129, 16), (15129, 1))

In [228]:
x_casas_teste_scaler.shape, y_casas_teste_scaler.shape

((6484, 16), (6484, 1))

In [230]:
regressor_svr_casas = SVR(kernel='rbf')
regressor_svr_casas.fit(x_casas_treinamento_scaler, y_casas_treinamento_scaler.ravel())

SVR()

In [232]:
regressor_svr_casas.score(x_casas_treinamento_scaler, y_casas_treinamento_scaler)

0.8123337393146999

In [233]:
regressor_svr_casas.score(x_casas_teste_scaler, y_casas_teste_scaler)

0.7339158652152076

In [237]:
previsoes = regressor_svr_casas.predict(x_casas_teste_scaler)
previsoes

array([-0.54877296,  3.48844091,  0.01692247, ..., -0.43360248,
       -0.92110462, -1.041454  ])

In [236]:
y_casas_teste_scaler

array([[-0.65279094],
       [ 2.80442566],
       [ 0.06267207],
       ...,
       [-0.42878706],
       [-0.73105736],
       [-0.89838556]])

In [240]:
y_casas_teste_inverse = scaler_y_casas.inverse_transform(y_casas_teste_scaler)
previsoes_inverse = scaler_y_casas.inverse_transform(previsoes.reshape(-1, 1))

In [241]:
y_casas_teste_inverse

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [242]:
previsoes_inverse

array([[ 335541.70853831],
       [1831447.68122609],
       [ 545148.43144492],
       ...,
       [ 378215.7461407 ],
       [ 197581.92515722],
       [ 152988.95642719]])

In [243]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_casas_teste_inverse, previsoes_inverse)

83085.30908154699