Random Forest

In [15]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

Base Plano de saúde

In [16]:
base_plano_saude2 = pd.read_csv('../plano_saude2.csv')
x_plano_saude2 = base_plano_saude2.iloc[:, 0:1].values
y_plano_saude2 = base_plano_saude2.iloc[:, 1].values
x_teste_arvore = np.arange(min(x_plano_saude2), max(x_plano_saude2), 0.1)
x_teste_arvore = x_teste_arvore.reshape(-1, 1)

In [17]:
from sklearn.ensemble import RandomForestRegressor
regressor_random_forest_saude = RandomForestRegressor(n_estimators= 10)
regressor_random_forest_saude.fit(x_plano_saude2, y_plano_saude2)

RandomForestRegressor(n_estimators=10)

In [18]:
regressor_random_forest_saude.score(x_plano_saude2, y_plano_saude2)

0.9638228231061655

In [19]:
grafico = px.scatter(x= x_plano_saude2.ravel(), y= y_plano_saude2)
grafico.add_scatter(x= x_teste_arvore.ravel(), y= regressor_random_forest_saude.predict(x_teste_arvore), name= 'Regressão')
grafico.show()

In [22]:
regressor_random_forest_saude.predict([[40]])

array([1429.])

Base Preço das Casas - 68151.8181 - 87,90

In [20]:
base_casas = pd.read_csv('../house_prices.csv')
x_casas = base_casas.iloc[:, 3:19].values
y_casas = base_casas.iloc[: ,2].values
x_casas_treinamento, x_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(x_casas, y_casas, test_size = 0.3, random_state = 0)

In [24]:
regressor_random_forest_casas = RandomForestRegressor(n_estimators=100)
regressor_random_forest_casas.fit(x_casas_treinamento, y_casas_treinamento)

RandomForestRegressor()

In [25]:
regressor_random_forest_casas.score(x_casas_treinamento, y_casas_treinamento)

0.9814595912607287

In [26]:
regressor_random_forest_casas.score(x_casas_teste, y_casas_teste)

0.8790053501030515

In [28]:
previsoes = regressor_random_forest_casas.predict(x_casas_teste)
previsoes

array([ 314530.        , 1791763.3       ,  517623.        , ...,
        372456.29666667,  237010.        ,  200837.62      ])

In [29]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [30]:
mean_absolute_error(y_casas_teste, previsoes)

68151.81817780397